{{- if .Values.security.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "low-code-assistant.fullname" . }}
  labels:
    {{- include "low-code-assistant.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "low-code-assistant.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  {{- with .Values.security.networkPolicy.ingressRules }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  egress:
  - {}
{{- end }}
