apiVersion: v1
kind: Secret
metadata:
  name: {{ include "low-code-assistant.fullname" . }}-secrets
  labels:
    {{- include "low-code-assistant.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.openaiApiKey }}
  OPENAI_API_KEY: {{ .Values.openaiApiKey | b64enc | quote }}
  {{- else }}
  # This is a placeholder. You should provide the API key using Helm values or a secrets management solution
  OPENAI_API_KEY: ""
  {{- end }}
